# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: FleetManager-CI

queue: 'Hosted Linux Preview'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - RobotOrchestrator/*
    - RobotOrchestrator.FleetManager/*

variables:
  buildConfiguration: 'Release'
  projectPath: 'RobotOrchestrator.FleetManager/RobotOrchestrator.FleetManager.csproj'
  testPath: 'RobotOrchestrator.FleetManager.Tests/RobotOrchestrator.FleetManager.Tests.csproj'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration) $(projectPath)
    dotnet test --configuration $(buildConfiguration) --logger trx $(testPath)
  displayName: Build and Test Dotnet Project
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: Publish Test Results
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: False
    projects: $(projectPath)
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'


